language: java
jdk:
  - oraclejdk9
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
# language: generic

# jobs:
#  include:
#      - stage: "Tests"                # naming the Tests stage
#      name: "Unit Tests"            # names the first Tests stage job
#      script: chmod +x ./app/src/test/java/com/plandora/*
#    - script: ./integration-tests
#      name: "Integration Tests"     # names the second Tests stage job
#    - stage: deploy
#      name: "Deploy to GCP"
#      script: ./deploy
